apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "pv0001"
spec:
  capacity:
    storage: "10Gi"
  accessModes:
    - "ReadWriteOnce"
  nfs:
    path: "/nfs/pv0001/"
    server: "192.168.3.151"
  persistentVolumeReclaimPolicy: "Recycle"